### ISSUE TITLE
Return all route data from getRoute

### ISSUE THREAD

**Issue by mychidarko** [leafsphp/router#3]
Get route currently only returns the route path and route method. Would be nice if all route config is returned instead.

**Comment by henry5059** [comment]
Ok, in the meantime I get the name by fetching all the paths and getting the particular name through the path. That being said, thank you very much for the information, it is really appreciated.

**Comment by mychidarko** [comment]
You can update Leaf and try again @henry5059

**Comment by henry5059** [comment]
Ok, thanks you very much.

**Comment by mychidarko** [comment]
Can I close this issue now?

**Comment by henry5059** [comment]
Yes
